config/routes.rb
Rails.application.routes.draw do
  

  

  root 'home#index'
  get '/cats/search', to: 'cats#search'
  resources :cats
  resources :owners

end

app/models/cat.rb
class Cat < ActiveRecord::Base


	validates_presence_of :name 

	belongs_to :owner

end

app/models/owner.rb
class Owner < ActiveRecord::Base

	 validates_presence_of :name

	 has_many :cats, dependent: :destroy


	 accepts_nested_attributes_for :cats,
           reject_if: lambda { |cat_attrs| cat_attrs['name'].blank? }
 # It won't save it if the cat has no name
	 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  
 before_filter :assign_cat, only: [:show, :destroy]


  def index

  	@cats = Cat.all

  end

  def search

		search_term = params[:name]

  if search_term == '' || search_term.nil?
  	@cats =[]
  else
		@cats = Cat.where(['name LIKE ?', "%#{search_term}%"])
	end

  end

  def new

  	@cat = Cat.new 

  end


  def edit

  	@cat = Cat.find(params[:id])

  end

  def create

  	@cat = Cat.new(cat_params)

  	if @cat.save
  		redirect_to cats_url
  	else
  		render :new
  	end

  end

  def show
  	
  end

  def destroy
  	
  	@cat.destroy
		redirect_to cats_url

  end

  private

  def cat_params
  	params.require(:cat).permit(:name, :birthday)
  end


  def assign_cat
  	@cat = Cat.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
     @owner.cats.build

  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:name,cats_attributes: [:id, :name, :birthday])

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/cats/_cats.html.erb
<% @cats.each do |cat| %>

  <li>

    <%= cat.name %>

    <span class='birthday'>

      <!-- Only format the date if birth_date exists -->
      <%= cat.birthday.to_s(:short) if cat.birthday %>

    </span>

    <span class='actions'>
      <%= link_to "More Info", cat_path(cat) %>
      <%= link_to "Delete", cat_path(cat), method: :delete,
                                  data: { confirm: "Are you sure?" }%>
    </span>

    <strong>
      <!-- Check if it has no owner, display it -->
      <%= cat.owner.nil? ? "No Owner" :

                           link_to("Has an owner", cat.owner) %>
    </strong>

  </li>

<% end %>

app/views/cats/create.html.erb
<h1>Cats#create</h1>
<p>Find me in app/views/cats/create.html.erb</p>

app/views/cats/index.html.erb
<h1>All the LOLcats!!!1</h1>

<p><%= link_to "New LOLcat", new_cat_path %></p>

<div class="cats-list">

  <ul>

    <%= render 'cats' %>

  </ul>

</div>

app/views/cats/new.html.erb
<h1>Cats#new</h1>


<%= form_for @cat do |f| %>

	<% if @cat.errors.any? %>
    <div class="form-errors">
      <ul>
        <% @cat.errors.full_messages.each do |message| %>
          <li><%=message%></li>
        <% end %>
      </ul>
    </div>
  <% end %>

		<p>

		<%= f.label :name %>
		<%= f.text_field :name, class: "input_name" %>
		</p>
		
		<p>

		<%= f.label :birthday %>
		<%= f.date_select :birthday, class: "input_birthday"  %>
		</p>

<p>

<%= f.submit %>
</p>

<% end %>

app/views/cats/search.html.erb
<h1> Search all the cats </h1>

<%= form_tag cats_search_path, method: :get do %>
	
	<%= search_field_tag :name %>
	
	<%= submit_tag 'Search', name: nil %>

<% end %>

<% if @cats.any? %>

	<h2> Search results </h2> 

	<%= render 'cats' %>

<% end %>

app/views/cats/show.html.erb
<h1> cat information </h1>

The cat name is <%= @cat.name %>
The cat birthday is <%= @cat.birthday %>

<br/>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>

<ul>
	<li><%= link_to "Cats", cats_url %></li>
	<li><%= link_to "Search", cats_search_path %></li>
	<li><%= link_to "Owners", owners_url %></li>
	<li></li>
</ul>

</nav>

<%= yield %>

</body>
</html>

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>


  <div class="field">

    <h2>Cats</h2>

    <!-- Look at the @owner.cats relationship
         and construct a form for each cat -->
    <%= f.fields_for :cats do |cf| %>

      <%= cf.label :name %><br>
      <%= cf.text_field :name %>

    <% end %>

  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<h1>Listing owners</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.name %></td>
        <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Owner', new_owner_path %>

app/views/owners/new.html.erb
<h1>New owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @owner.name %>
</p>

<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>